# Generated by Django 2.2.1 on 2019-05-24 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200)),
                ('subject_code', models.CharField(max_length=120, unique=True)),
                ('unit1_syllabus', models.TextField(blank=True, max_length=1000, null=True)),
                ('unit2_syllabus', models.TextField(blank=True, max_length=1000, null=True)),
                ('unit3_syllabus', models.TextField(blank=True, max_length=1000, null=True)),
                ('unit4_syllabus', models.TextField(blank=True, max_length=1000, null=True)),
                ('exam_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=200)),
                ('unit_part_1', models.CharField(max_length=500)),
                ('unit_part_1_syllabus', models.TextField(max_length=1000)),
                ('unit_part_2', models.CharField(blank=True, max_length=500, null=True)),
                ('unit_part_2_syllabus', models.TextField(blank=True, max_length=1000, null=True)),
                ('unit_part_3', models.CharField(blank=True, max_length=500, null=True)),
                ('unit_part_3_syllabus', models.TextField(blank=True, max_length=1000, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='books.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='UnitParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_head', models.CharField(max_length=500)),
                ('part_syllabus', models.TextField(max_length=1000)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_parts', to='books.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField()),
                ('unit_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='books.UnitParts')),
            ],
        ),
        migrations.CreateModel(
            name='Related',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_done', models.BooleanField(default=False)),
                ('unit_1_done', models.BooleanField(default=False)),
                ('unit_2_done', models.BooleanField(default=False)),
                ('unit_3_done', models.BooleanField(default=False)),
                ('unit_4_done', models.BooleanField(default=False)),
                ('subject', models.ManyToManyField(to='books.Subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
