# Generated by Django 2.2.1 on 2019-05-24 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_topic_slug_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='slug_field',
            new_name='slug',
        ),
    ]
