# Generated by Django 2.2.1 on 2019-05-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20190524_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='google_data',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
