# Generated by Django 2.2.6 on 2019-10-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_topic_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
