# Generated by Django 2.2.6 on 2019-10-22 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20191022_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='text_book_name',
        ),
    ]
