# Generated by Django 2.2.6 on 2019-10-25 14:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0009_remove_subject_text_book_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic_Links',
            new_name='TopicResources',
        ),
    ]
