# Generated by Django 2.2.6 on 2019-10-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20191025_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicresources',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
