# Generated by Django 2.2.6 on 2019-10-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_topicresources_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicresources',
            name='rating',
        ),
        migrations.AddField(
            model_name='topicresources',
            name='endorsed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topicresources',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
