# Generated by Django 2.2.6 on 2019-10-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_auto_20191025_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='slug',
            field=models.SlugField(default='q'),
            preserve_default=False,
        ),
    ]
